### ISSUE TITLE
How to show imaes in landscape mode using SSImageBrowser

### ISSUE THREAD

**Issue by WarisSaqi** [CodeEagle/SSImageBrowser#12]
I want to show the images in landscape mode too. Only the images showing from SSImageBrowse.
Is this library is support landscape?

**Comment by CodeEagle** [comment]
I need to check it out...

**Comment by CodeEagle** [comment]
@WarisSaqi now it works

**Comment by WarisSaqi** [comment]
@CodeEagle, What i need to do for this?

**Comment by CodeEagle** [comment]
![image](https://cloud.githubusercontent.com/assets/2311352/20055369/a7fa1cd4-a51b-11e6-946e-f50592cb4ce5.png)
