### ISSUE TITLE
Urgently need the older version 2.0.9

### ISSUE THREAD

**Issue by tonifirnandes** [CodeEagle/SSImageBrowser#18]
Dear team, sorry i am maintaining older iOS project which still using SSImageBrowser library version 2.0.9, unfortunately we are missing the generated podsfile previously, so when we do pod install to get the lib it's not compatible again with our project. If you don't mind, please provide us pod with version 2.0.9 which still support swift 2.

Some errors like this : 
![image](https://user-images.githubusercontent.com/3122029/39066535-9b257a50-44ff-11e8-9513-d8be7ba6841d.png)

Thanks for your kinda help.

**Comment by CodeEagle** [comment]
Hi @tonifirnandes ,done

**Comment by tonifirnandes** [comment]
Thank you very much sir, once again we are really sorry about this, we'll inform you later if we have migrated to newer version of swift so no need to keep the version "2.0.9" anymore.
