### ISSUE TITLE
Error when using XCode 7.1

### ISSUE THREAD

**Issue by russellbrooks** [CodeEagle/SSImageBrowser#3]
Updated to XCode 7.1 and receive the following errors:

.../Pods/pop/pop/POP.h:13:9: Include of non-modular header inside framework module 'pop.POP'
.../Pods/pop/pop/POP.h:15:9: Include of non-modular header inside framework module 'pop.POP'
.../Pods/pop/pop/POP.h:16:9: Include of non-modular header inside framework module 'pop.POP'
... same for every import until the last
.../Pods/pop/pop/POP.h:27:9: Include of non-modular header inside framework module 'pop.POP'

I have tried the suggested solution posted to StackOverflow (https://stackoverflow.com/questions/27776497/include-of-non-modular-header-inside-framework-module) but it did not work.

**Comment by CodeEagle** [comment]
https://github.com/facebook/pop/issues/285

``` ruby 
post_install do |installer|
    `find Pods -regex 'Pods/pop.*\\.h' -print0 | xargs -0 sed -i '' 's/\\(<\\)pop\\/\\(.*\\)\\(>\\)/\\"\\2\\"/'`
end

try this

**Comment by russellbrooks** [comment]
Excellent find and impressive response time! That fixed the first error but this minor syntax bug came up

.../Pods/SSImageBrowser/Source/SSPhoto.swift:160:25: Reference to property 'progressUpdateBlock' in closure requires explicit 'self.' to make capture semantics explicit

After adding in the updated syntax, everything works perfectly. Thanks again!
