### ISSUE TITLE
Caption view will not update its frame when you rotate the device

### ISSUE THREAD

**Issue by gujinku** [CodeEagle/SSImageBrowser#6]
Root cause:
extension SSCaptionView {
    func setBackground() {
        let fadeView = UIView(frame:CGRectMake(0, -100, **_UIScreen.mainScreen().bounds.width_**, 130+100)) // Static width, autoresizingMask is not working
...
    }
}

the original value is 10000. Not sure why did you change it?  In this case, the fadeView width will be fixed as UIScreen.mainScreen().bounds.width. Did you mean:

max (UIScreen.mainScreen().bounds.width, UIScreen.mainScreen().bounds.height)) 

??

**Comment by CodeEagle** [comment]
maybe you're right.
