### ISSUE TITLE
Crash issue:  Swipe the photos when they are downloading in "Photos from Flickr"

### ISSUE THREAD

**Issue by gujinku** [CodeEagle/SSImageBrowser#7]
Pre-condition: Simulate bad network. There are several images to download, you try to preview them by swiping.

In "private func configurePage(page: SSZoomingScrollView, forIndex index: Int)", you used "[unowned page]"

It will cause crash. I replaced it with "[weak page]" resolved the crash issue.

**Comment by CodeEagle** [comment]
thanks, you can pull a pr

**Comment by rpzzzzzz** [comment]
Is this bug still exist? 
I found it in 	
public func setProgress(progress: CGFloat, forPhoto aPhoto: SSPhoto!)

**Comment by CodeEagle** [comment]
[file here](https://github.com/CodeEagle/SSImageBrowser/commit/4fe9752b9390a9fd90be8255f776db1adfa5d021)
at line 1044 on right,already changed to `weak`

**Comment by noobywalker** [comment]
@rpzzzzzz @CodeEagle I have made aPhoto optional for 
public func setProgress(progress: CGFloat, forPhoto aPhoto: SSPhoto!) function to avoid quick swipe crash.
this [pull request](https://github.com/CodeEagle/SSImageBrowser/pull/11)

**Comment by CodeEagle** [comment]
thanks alot
