### ISSUE TITLE
Memory Issue: The memory will keep increasing while you browse the images

### ISSUE THREAD

**Issue by gujinku** [CodeEagle/SSImageBrowser#8]
You can compare the SSImageBrowser and IDMPhotoBrowser.

**Comment by CodeEagle** [comment]
kkk，any idea for this issue?

**Comment by gujinku** [comment]
During the last several days, I kept thinking it's SDWebImage's issue. 
After comparing the code between these two libraries, **it turns out that there is a retain cycle**. 

SSTapDetectingImageView:  please add "weak" keyword for "tapDelegate" property
SSTapDetectingView: please add "weak" keyword  for "tapDelegate" property.

**Comment by CodeEagle** [comment]
thanks a lot！！！！

**Comment by gujinku** [comment]
My pleasure :)
